version: '2'
services:
    web:
        container_name: fuel_web
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./www:/var/www
            - ./config/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "10080:80"
        links:
            - app
    app:
        container_name: fuel_app
        build: 
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./www:/var/www
        links:
            - mysql
            - redis
    mysql:
        container_name: fuel_mysql
        restart: always
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "33060:3306"
    redis:
        container_name: fuel_redis
        restart: always
        image: redis:latest
        ports:
            - "63790:6379"
        command: redis-server --appendonly yes
